project:
  type: website
  output-dir: docs

website:
  title: "Elecciones Legislativas CABA 2025"


format:
  html:
    theme: cosmo
    include-in-header:
      - text: |
          <link rel="stylesheet" href="/_extensions/qmd-lab/closeread/closeread.css">
    resources:
      - _extensions/qmd-lab/closeread/closeread.css
      - _extensions/qmd-lab/closeread/closeread.js